AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation Template for Cavendish's Shared Resources

Resources:
  siteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: louie-snake-cloud
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: louie-snake-cloud