name: Infra CICD 
on:
  pull_request:
  push:
    branches:
      - main 
      - infra
jobs:
  cloudformation-infra:
    name: Deploy Stack to AWS 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: List Contents of Directory
        run: ls

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Stack 
        id: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          no-fail-on-empty-changeset: "1"
          name: snake-louie-cloud-infra
          template: infra/infra_cf.yml

  deploy-react-app:
    name: Deploy React App
    runs-on: ubuntu-latest
    needs: cloudformation-infra
    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      run: |
        cd snake-louie-cloud
        yarn install
    - name: Production Build
      run: |
        cd snake-louie-cloud
        yarn build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: louie-snake-cloud
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "snake-louie-cloud/build"

  cloudformation-cert:
    name: Deploy Stack to AWS (Cert)
    runs-on: ubuntu-latest
    needs: deploy-react-app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials (Cert)
        id: creds-cert
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy CloudFormation Stack 
        id: cert-deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: snake-louie-cloud-infra-cert
          no-fail-on-empty-changeset: "1"
          template: infra/cert_cf.yml
      
